apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  interval: 5m
  chart:
    spec:
      chart: contour
      version: "9.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: bitnami
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    global:
      storageClass: tanzu
